name: Sim tests

on: [pull_request, push]

jobs:
  tests-sim:
    name: Sim tests
    runs-on: ubuntu-latest
    steps:
      # <common-build> - Uses YAML anchors in the future
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14.16.0"
      - name: Restore dependencies
        uses: actions/cache@master
        id: cache-deps
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-ignore-optional-14.16.0
      - name: Install & build
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile --ignore-optional
      - name: Build
        run: yarn build
        if: steps.cache-deps.outputs.cache-hit == 'true'
      # </common-build>

      # - name: Simulation single process single node test
      #   run: yarn test:sim:singleProcess
      #   working-directory: packages/lodestar
      # - name: Simulation single process multi node test
      #   run: yarn test:sim:singleProcessMultiNode
      #   working-directory: packages/lodestar
      - name: Simulation multi process multi node test phase0
        run: yarn test:sim:multiProcess
        working-directory: packages/lodestar
        env: {RUN_ONLY_SIM_TEST: phase0}
      - name: Simulation multi process multi node test altair epoch genesis
        run: yarn test:sim:multiProcess
        working-directory: packages/lodestar
        env: {RUN_ONLY_SIM_TEST: altair-genesis}
      - name: Simulation multi process multi node test altair epoch 2
        run: yarn test:sim:multiProcess
        working-directory: packages/lodestar
        env: {RUN_ONLY_SIM_TEST: altair-epoch2}
      - name: Upload debug log test files
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: debug-test-logs
          path: packages/lodestar/test-logs
